name: GID
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  font_awesome_flutter: ^10.1.0
  gap: ^2.0.0
  get: ^4.6.5
  get_it: ^6.0.0
  get_storage: 2.0.3
  image_picker: ^0.8.5+3
  internet_connection_checker: ^1.0.0+1
  pull_to_refresh: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 200
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 300
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

